### ISSUE TITLE
Improvements to the on-boarding process documentation

### ISSUE THREAD

**Issue by frosty-geek** [SovereignCloudStack/Docs#10]
In the process of merging the contribution guide SovereignCloudStack/contributor-guide#34 with this repo, I would propose to include a reference to the gaia-x community on-boarding guide once it has been clarified see [gitlab Issue](https://gitlab.com/gaia-x/gaia-x-community/operational-handbook/-/issues/6).

Would you agree with this proposal? ;-)

**Comment by garloff** [comment]
I would agree, absolutely.
Unfortunately, there does not seem to be progress upstream.

**Comment by tibeer** [comment]
There is and will be no Onboarding Guide. Real onboarding can unfortunately only happen if you are in the intranet and have access to the restricted services ( [gitlab](https://gitlab.com/gaia-x/gaia-x-community), [nextcloud](https://community.gaia-x.eu/apps/dashboard/), [intranet](https://members.gaia-x.eu/) )
For completeness - link to operational handbook: https://gaia-x.gitlab.io/technical-committee/operational-handbook/

@garloff this can be closed.
