### ISSUE TITLE
Release Notes for R3

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/Docs#100]
We have started to collect the central pieces of the release notes.
Please have a look at https://github.com/SovereignCloudStack/Docs/blob/feat/RelNotes3/Release-Notes/Release3.md in branch feat/RelNotes3 of this Docs repository.
Pull requests and comments are more than welcome!

**Comment by fkr** [comment]
@ra-beer will assure that their parts are filled in:

* especially Upgrade / Migration notes

**Comment by berendt** [comment]
Jens has already added things here. The details of the OSISM release are in https://github.com/osism/release/blob/main/notes/4.0.0/NOTES.md. Should all this be included here or should we include a reference to it?

**Comment by fkr** [comment]
@berendt the important parts are the upgrade / migration notes - the rest has been dealt with (as you also commented). @matfechner took couple items for that from the current pco/wavecon session.

**Comment by berendt** [comment]
Ok. Then important notes for the upgrade are added that are now dropped during the tests.
