### ISSUE TITLE
For Operators - Rewrite Introduction

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/docs#103]

**Comment by fdobrovolny** [comment]
About

> As only the sum of different repositories complete the SCS Stack, it is important to have an easy and accessible documentation in one place.

This sentence is out of place remove

**Comment by harmathy** [comment]
There should be a reference on how to contribute to the documentation at the very beginning

**Comment by chrisschwa** [comment]
```
What is SCS? Why should I care?
SCS describes a standard as well as a reference implementation of this standard.

Please see our [public web site](https://scs.community/) and specifically the [About SCS](https://scs.community/About/) page.
```

This Part should be removed, because if you are in the Docs you already "Care".

**Comment by harmathy** [comment]
We need an architectural overview and list what technologies are used

**Comment by chrisschwa** [comment]
# The reference implementation
Under that we need to have a description what the Testbed actually is and specifically what it is NOT.
After reading that part the reader should be able to decide if he needs a testbed implementation or something else.

**Comment by maxwolfs** [comment]
> We need an architectural overview and list what technologies are used

... using the background container from #102 and go deeper with specific ingredients.

<img width="917" alt="Bildschirmfoto 2023-11-08 um 10 50 14" src="https://github.com/SovereignCloudStack/docs/assets/28341836/9e7d1d09-f300-43c4-a82b-70b440796163">

**Comment by maxwolfs** [comment]
We need a container layer section after the reference implementation section stating use cases to get started with it - with or without the iaas layer/reference implementation and linking to already existing examples and to the container layer introduction, with the still to come #99.

**Comment by maxwolfs** [comment]
## Development of SCS

While the SCS projects tracks the efforts across the released in [epics and userstories](https://github.com/orgs/SovereignCloudStack/projects), the work on the code happens upstream - as such these repositories are usually not found in the SCS GitHub organization. The place for any issues regarding SCS is [here](https://github.com/SovereignCloudStack/issues/issues). Whenever possible SCS works directly in the upstream projects into
* CNCF projects
* OpenStack, 
* kolla-ansible, 
* OSISM and others.
