### ISSUE TITLE
nbde.md - is this for hypervisor encryption?

### ISSUE THREAD

**Issue by neuroserve** [SovereignCloudStack/Docs#139]
Hi *,
as ndbe is mentioned in the Release Notes: Is this for hypervisor encryption? How would that be integrated in the installation process? Would that be an addition for the operation docs?

**Comment by itrich** [comment]
We have covered some insights to NBDE here: https://scs.community/2022/08/17/osism-nbde-install/

Please let me know if you have further questions that haven't been covered by the above article. I'm happy to connect you to the right people in our community.

**Comment by neuroserve** [comment]
That's a good start, thanks. Maybe we should add that Link to somewhere in the Docs tree, anyways.

**Comment by fkr** [comment]
@neuroserve this is covered in the OSISM docs, since it is an OSISM feature: https://docs.osism.tech/configuration/environments/infrastructure/nbde.html

**Comment by neuroserve** [comment]
Thanks for the pointer!
