### ISSUE TITLE
Standards/Certified clouds: Create a multiline entry for the four PCO regions

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/docs#165]
We'd like to improve the layout of the list of certified clouds at https://docs.scs.community/standards/certification/overview:
The four regions prod1 ... prod 4 should have a multiline entry in the table where we write plusserver only once, but can have a per region name (region prod1 ... region prod4) and a compliant label and health-mon link per region as well.

**Comment by frosty-geek** [comment]
@maxwolfs well we can just add all the regions to the same field and user '<br>'-tags
