### ISSUE TITLE
Proposal to Enhance SCS Documentation with a Detailed Deployment Tutorial

### ISSUE THREAD

**Issue by maxwolfs** [SovereignCloudStack/docs#181]
### Introduction
We propose to enrich the Sovereign Cloud Stack (SCS) documentation by adding a detailed deployment tutorial based on a real-world use case based on Artcodix deployment. This tutorial will illustrate one of many potential solutions for deploying SCS, emphasizing that it does not prescribe the only approach but showcases a viable path that has been effective in our experience.

### Objective
The primary goal of this contribution is to make the extensive capabilities of SCS more accessible to new users and to facilitate a deeper understanding of its deployment mechanisms. By providing a step-by-step guide, we intend to help users not only learn the operational aspects of SCS but also encourage them to experiment and adapt the process according to their unique requirements.

This addition is intended as a _tutorial_, rather than a quick how-to guide, following the diataxis framework (https://diataxis.fr/tutorials-how-to/#understanding-the-distinction). It is designed to offer a comprehensive learning experience, guiding users from the basics to a complete setup, thereby enabling enabling them to understand relevant considerations appropriate for similar sized setups and apply the learning to initiate their own deployments.

**Comment by berendt** [comment]
It would be important to go into detail into the steps that need to be taken to prepare a deployment (cookiecutter, configuration repository, network configuration, Ceph configuration, TLS certificates, ...). So that we don't just have the pure deployment process, but also how to get there in order to be able to make a deployment.
