### ISSUE TITLE
Add csctl

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/docs#228]
Add docs from https://github.com/SovereignCloudStack/csctl and https://github.com/SovereignCloudStack/csctl-plugin-openstack to the [Contributors Docs](https://docs.scs.community/contributor-docs/development/)

**Comment by DEiselt** [comment]
Created https://github.com/SovereignCloudStack/csctl/issues/149 and https://github.com/SovereignCloudStack/csctl/pull/150 for this.
