### ISSUE TITLE
Add table of with status of SCS standards

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/docs#29]
As a user, I want to see the current status of SCS standards. Copy tables form [slide 17 - 25](https://scs.sovereignit.de/nextcloud/apps/files/?dir=/Sovereign%20Cloud%20Stack/Presentations/Alasca-202302&openfile=181235) to docs repo.

**Comment by mbuechse** [comment]
Current development happens inside [HedgeDoc](https://input.scs.community/tqKlv1Z_Srmi5e5o76CxhQ).
The [guide](https://docs.scs.community/community/community/contribute/adding-docs-guide) tells us where to place documentation. Still unsure where to put it. @garloff What do you think?

**Comment by fkr** [comment]
> A master issue that links the others would be useful. (Use - [ ] syntax.)

I'd suggest to make an epic that contains each standard as a story.
Definition of Done for the epic contains of that said list (that contains the stories).

**Comment by mbuechse** [comment]
So, if I understand your proposals correctly: both of you suggest to use one issue per row of the table; sometimes such an issue already exists, sometimes it needs to be created. Moreover, we might use (1) a master issue with tasks corresponding to these aforementioned issues or (2) an epic linking these issues. Now another option occurs to me: (3) tag the issues and use the board to track them -- in fact, one such board already seems to exist: https://github.com/orgs/SovereignCloudStack/projects/6/views/23?layout=board

Questions:
How do you like this third option?
Is the board the right one, or would we use/create another one?

Also, I suppose we should keep these issues up to date, referencing any relevant documents, issues, discussions etc., so as to have a single ~~source~~ sink of truth?

**Comment by maxwolfs** [comment]
There is also this issue within the docs-page repository with the aim of an interactive overview of available, I'm currently on: https://github.com/SovereignCloudStack/docs-page/issues/41  
Feedback welcomed! :)

(going back to this one: https://github.com/SovereignCloudStack/standards/issues/86)

**Comment by mbuechse** [comment]
@maxwolfs Thanks for pointing me to this issue. If I understand correctly, the aim is to convert the YAML file(s) into an interactive diagram, which I do like. I think the epic that @fkr suggested would be a good place for organizing the to-dos, whereas the diagram would mainly show what's already done, right?

BTW, I just noticed that the [YAML]( https://github.com/SovereignCloudStack/standards/blob/main/Tests/scs-compatible.yaml) claims that V2 of "SCS compatible" (a) has been stabilized on 2023-03-23 and (b) it contains the flavor naming standard. However, the latter standard hasn't been stabilized yet. @garloff Is that a contradiction, or are these different concepts of stabilization? (NB I don't mean to be nitpicking here; I'm still familiarizing myself with the topic, and as yet I can't tell with certainty what's problematic and what isn't.)

**Comment by maxwolfs** [comment]
> @maxwolfs Thanks for pointing me to this issue. If I understand correctly, the aim is to convert the YAML file(s) into an interactive diagram, which I do like. I think the epic that @fkr suggested would be a good place for organizing the to-dos, whereas the diagram would mainly show what's already done, right?

Yes, you are correct.

**Comment by mbuechse** [comment]
Will be covered via
- https://github.com/SovereignCloudStack/docs-page/issues/41 regarding certification
- https://github.com/SovereignCloudStack/standards/issues/285 regarding IaaS standards
- https://github.com/SovereignCloudStack/issues/issues/181 regarding CaaS standards
