### ISSUE TITLE
Enable GitHub Discussions for project

### ISSUE THREAD

**Issue by noonedeadpunk** [SovereignCloudStack/Docs#35]
**Issue description**

Currently there's no effective way to discuss Drafts and suggestions that have been already merged. Raising an issue for open discussion of some point of the documents might be demotivating potential contributors since it might be not really an issue but suggestion in format of open discussion. At the same time issues are tend to be used for design flaws or some missing things.

**Suggested solution**

Enable [GitHub Discussions](https://docs.github.com/en/discussions) functionality and start new thread for each new draft that is landed. This will allow potential contributors to feel more open to participate and have an efficient async topics regarding each document that anybody can join.

**Comment by fkr** [comment]
Just to throw something out that has been tickling my mind: I'd really like to have something like that. Personally I've not worked much with Github Discussions, BUT in other projects I really enjoy having a place where things can be discussed asynchronously.
So I'd give this a 👍 .

@itrich what is your take on this?

**Comment by fkr** [comment]
Apparently (looking at the Docs/ Repo) GH discussions is enabled. I'll close this issue and will do a testdrive with the GH discussions next time an item comes up.
