### ISSUE TITLE
broken links in docs pages on 

### ISSUE THREAD

**Issue by alexander-diab** [SovereignCloudStack/docs#4]
In the standards, conformity and certification the links to the standards and to the draft document are 404.

**Comment by frosty-geek** [comment]
| Error          | Deadlink                                                                                                                                   | Hint                       | On Page                                                                 |
|----------------|--------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|-------------------------------------------------------------------------|
| Host not found | https://docs.scs.community.com/docs/intro                                                                                                  | Social meta tag Outbound   | https://docs.scs.community/docs/intro/                                  |
| 404 Not found  | https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/flavor-naming.md                                                         | a_href Outbound            | https://docs.scs.community/docs/intro/                                  |
| 404 Not found  | https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/Image-Properties-Spec.md                                                 | a_href Outbound            | https://docs.scs.community/docs/intro/                                  |
| 404 Not found  | https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/SCS-Spec.md                                                              | a_href Outbound            | https://docs.scs.community/docs/intro/                                  |
| Host not found | https://docs.scs.community.com/                                                                                                            | Social meta tag Outbound   | https://docs.scs.community/                                             |
| Host not found | https://docs.scs.community.com/community/                                                                                                  | Social meta tag Outbound   | https://docs.scs.community/community/ and 1 more                        |
| Host not found | https://docs.scs.community.com/docs/category/openstack-image-manager                                                                       | Social meta tag Outbound   | https://docs.scs.community/docs/category/openstack-image-manager/       |
| Host not found | https://docs.scs.community.com/docs/category/release-notes                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/category/release-notes/                 |
| Host not found | https://docs.scs.community.com/docs/glossary                                                                                               | Social meta tag Outbound   | https://docs.scs.community/docs/glossary/                               |
| Host not found | https://docs.scs.community.com/docs/release-notes/Release0                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/release-notes/Release0/                 |
| Host not found | https://docs.scs.community.com/docs/release-notes/Release1                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/release-notes/Release1/                 |
| Host not found | https://docs.scs.community.com/docs/release-notes/Release2                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/release-notes/Release2/                 |
| Host not found | https://docs.scs.community.com/docs/release-notes/Release3                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/release-notes/Release3/                 |
| Host not found | https://docs.scs.community.com/blog                                                                                                        | Social meta tag Outbound   | https://docs.scs.community/blog/                                        |
| 404 Not found  | https://github.com/SovereignCloudStack/Docs/blob/main/https://github.com/SovereignCloudStack/standards/tree/main/Design-Docs/monitoring.md | a_href Outbound            | https://docs.scs.community/docs/release-notes/Release1/                 |
| Host not found | https://gardener.io/                                                                                                                       | a_href Outbound            | https://docs.scs.community/docs/release-notes/Release1/                 |
| 404 Not found  | https://www.bsi.bund.de/EN/Topics/CloudComputing/Compliance_Criteria_Catalogue/Compliance_Criteria_Catalogue_node.html                     | a_href Outbound            | https://docs.scs.community/docs/release-notes/Release2/ and 1 more      |
| 404 Not found  | https://github.com/SovereignCloudStack/Docs/pull/26                                                                                        | a_href Outbound Redirected | https://docs.scs.community/docs/release-notes/Release2/                 |
| Host not found | https://docs.scs.community.com/community/calendar                                                                                          | Social meta tag Outbound   | https://docs.scs.community/community/calendar/                          |
| Host not found | https://docs.scs.community.com/docs/openstack-image-manager/overview                                                                       | Social meta tag Outbound   | https://docs.scs.community/docs/openstack-image-manager/overview/       |
| Host not found | https://docs.scs.community.com/community/contribute/collaboration                                                                          | Social meta tag Outbound   | https://docs.scs.community/community/contribute/collaboration/          |
| Host not found | https://docs.scs.community.com/docs/openstack-image-manager/quickstart                                                                     | Social meta tag Outbound   | https://docs.scs.community/docs/openstack-image-manager/quickstart/     |
| Host not found | https://docs.scs.community.com/docs/openstack-image-manager/requirements                                                                   | Social meta tag Outbound   | https://docs.scs.community/docs/openstack-image-manager/requirements/   |
| Host not found | https://docs.scs.community.com/docs/openstack-image-manager/configuration                                                                  | Social meta tag Outbound   | https://docs.scs.community/docs/openstack-image-manager/configuration/  |
| Host not found | https://docs.scs.community.com/docs/openstack-image-manager/contribute                                                                     | Social meta tag Outbound   | https://docs.scs.community/docs/openstack-image-manager/contribute/     |
| Host not found | https://docs.scs.community.com/docs/release-notes/Release4                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/release-notes/Release4/                 |
| Host not found | https://docs.scs.community.com/docs/release-notes/ReleaseX                                                                                 | Social meta tag Outbound   | https://docs.scs.community/docs/release-notes/ReleaseX/                 |
| Host not found | https://docs.scs.community.com/blog/welcome                                                                                                | Social meta tag Outbound   | https://docs.scs.community/blog/welcome/                                |
| Host not found | https://docs.scs.community.com/blog/mdx-blog-post                                                                                          | Social meta tag Outbound   | https://docs.scs.community/blog/mdx-blog-post/                          |
| Host not found | https://docs.scs.community.com/blog/long-blog-post                                                                                         | Social meta tag Outbound   | https://docs.scs.community/blog/long-blog-post/                         |
| Host not found | https://docs.scs.community.com/blog/first-blog-post                                                                                        | Social meta tag Outbound   | https://docs.scs.community/blog/first-blog-post/                        |
| Host not found | https://docs.scs.community.com/blog/tags/community                                                                                         | Social meta tag Outbound   | https://docs.scs.community/blog/tags/community/                         |
| Host not found | https://docs.scs.community.com/blog/tags/documentation                                                                                     | Social meta tag Outbound   | https://docs.scs.community/blog/tags/documentation/                     |
| Host not found | https://docs.scs.community.com/blog/tags/hello                                                                                             | Social meta tag Outbound   | https://docs.scs.community/blog/tags/hello/                             |
| Host not found | https://docs.scs.community.com/blog/tags/scs                                                                                               | Social meta tag Outbound   | https://docs.scs.community/blog/tags/scs/                               |
| Host not found | https://docs.scs.community.com/blog/tags/guide                                                                                             | Social meta tag Outbound   | https://docs.scs.community/blog/tags/guide/                             |
| Host not found | https://docs.scs.community.com/blog/tags/howto                                                                                             | Social meta tag Outbound   | https://docs.scs.community/blog/tags/howto/                             |
| Host not found | https://docs.scs.community.com/community/contribute/license-considerations                                                                 | Social meta tag Outbound   | https://docs.scs.community/community/contribute/license-considerations/ |
| 404 Not found  | https://opensource.org/licenses)-approved                                                                                                  | a_href Outbound            | https://docs.scs.community/community/contribute/license-considerations/ |
| Host not found | https://docs.scs.community.com/community/contribute/dco-and-licenses                                                                       | Social meta tag Outbound   | https://docs.scs.community/community/contribute/dco-and-licenses/       |
| 404 Not found  | https://en.wikipedia.org/wiki/Apache_License>                                                                                              | a_href Outbound Noindex    | https://docs.scs.community/community/contribute/license-considerations/ |
| Host not found | https://docs.scs.community.com/blog/tags                                                                                                   | Social meta tag Outbound   | https://docs.scs.community/blog/tags/                                   |

**Comment by frosty-geek** [comment]
SovereignCloudStack/docs#9 SovereignCloudStack/docs-page#35 SovereignCloudStack/release-notes#4 should fix the broken links mentioned [here](https://github.com/SovereignCloudStack/docs/issues/4#issuecomment-1426911508)
