### ISSUE TITLE
wrong link to cluster-api-provicer in README.md 

### ISSUE THREAD

**Issue by linwalth** [SovereignCloudStack/Docs#53]
The README.md has the wrong link to the capi provider as it links to a nonexistent page:
https://github.com/SovereignCloudStack/Docs/blob/main/README.md?plain=1#L42

The actual link is:
https://github.com/SovereignCloudStack/k8s-cluster-api-provider

**Comment by fkr** [comment]
thanks @linwalth . Fixed!
