### ISSUE TITLE
Add something similar to Homer

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/docs#63]
As suggested by @tibeer during the SIG Community, we should offer something similar to Homer for our contributors. A central page / dashboard should allow our day-to-day contributors to jump to all tools we're currently using.

The Homer project can be found here: https://github.com/bastienwirtz/homer
A demo application can be found here: https://homer-demo.netlify.app/

@tibeer already did some work here: https://github.com/tibeer/helm-charts/tree/gh-pages/scs-startpage

**Comment by tibeer** [comment]
Change link to a specific commit version since things changes during the time: https://github.com/tibeer/helm-charts/commit/d9ffb0a3bf30f3256a48be5dad7c6ab437299874
