### ISSUE TITLE
Nested Virtualization

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/Docs#87]
We currently don't have a way to express in the flavor name whether or not the flavors support nested virtualization.
We should expect nested virt to be default-on and have a modifier to show that it's off?

**Comment by garloff** [comment]
Our image names are short and have rather compressed information, so "-nonest" would seem better here.

There is one caveat:
* We have somer smaller cloud providers that have a relatively small variance in their hardware and that don't want to offer a ton of flavors that differ in some details.
* We can accommodate them with the current spec as it allows providers to *under*state the performance/properties and does not require to specifically list CPU generation etc. So short names like SCS-2V:8:20 can be used even for flavors that have a high-performance CPU inside.
* To make detailed flavor properties discoverable, we would need to standardize extra_specs then, which is an effort that is underway.
* If we make nested virtualization the default property, this would *require* the providers to either enable it in all flavors or to add "-nonest" to all flavors. Together with our set of mandatory flavors, we would basically force enabling nested virtuatlization on providers for a lot of their flavors. (While I like enabled nested virt, I feel nervous about forcing it on providers.)

By this logic, we should be careful about adding opt-out "-noXXX" suffices, as it creates a strong force on everyone to not opt out.

So my suggestion would be to
(a) Add an optional "-nest" name suffix to the spec
(b) Prioritize the work on a standardized set of extra_specs that ensure discoverability without encoding all details in the flavor name

and (different discussion):
(c) We probably need to explain the rationale of our flavor naming (and flavor extra_specs standardization) approach

**Comment by fkr** [comment]
I actually added this item to todays agenda for the SIG Standardization (see pad) yesterday to discuss it there. :)

**Comment by fkr** [comment]
#87 has been merged. As such, this issue can be closed. thanks @garloff!
